package vista;

import controlador.GestorTareas;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import modelo.Tarea;

/**
 * Clase principal de GestCourse que gestiona la Vista (interfaz de usuario) y el menú de la aplicación.
 * @autor [T] Adrián Díaz García
 */
public class Ventana_principal extends javax.swing.JFrame {
    
    private final GestorTareas controlador;
    
    public Ventana_principal() {
        initComponents();
        
        this.setTitle("Gestión de Tareas    |   GestCourse  |   Adrián Díaz García");
        
        controlador = new GestorTareas();
        
        cargarFechaActual();

        btnMenuNuevaTarea.setForeground(java.awt.Color.WHITE);
        btnMenuPendientes.setForeground(java.awt.Color.WHITE);
        btnMenuActualizar.setForeground(java.awt.Color.WHITE);
        btnMenuFinalizadas.setForeground(java.awt.Color.WHITE);
    }

    private void cargarFechaActual() {
        LocalDate fechaHoy = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtFechaCreacion.setText(fechaHoy.format(formato));
    }

    private void actualizarTabla(javax.swing.JTable tablaDestino, String estadoFiltro) {
        String[] columnas = {"Código", "Título", "Prioridad", "Módulo", "F. Creación", "F. Entrega", "Estado"};
        
        javax.swing.table.DefaultTableModel modeloTabla = new javax.swing.table.DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };
        
        for (Tarea t : controlador.obtenerTodasLasTareas()) {
            if (t.getEstado().equals(estadoFiltro)) {
                Object[] fila = {
                    t.getCodigo(),
                    t.getTitulo(),
                    t.getPrioridad(),
                    t.getModulo(),
                    t.getFechaCreacion(),
                    t.getFechaEntrega(),
                    t.getEstado()
                };
                modeloTabla.addRow(fila);
            }
        }
        
        tablaDestino.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlMenu = new javax.swing.JPanel();
        pnlBotones = new javax.swing.JPanel();
        btnMenuNuevaTarea = new javax.swing.JButton();
        btnMenuPendientes = new javax.swing.JButton();
        btnMenuActualizar = new javax.swing.JButton();
        btnMenuFinalizadas = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        pnlContenedor = new javax.swing.JPanel();
        pnlCrear = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        rbAlta = new javax.swing.JRadioButton();
        rbMedia = new javax.swing.JRadioButton();
        rbBaja = new javax.swing.JRadioButton();
        cbModulo = new javax.swing.JComboBox<>();
        txtFechaCreacion = new javax.swing.JTextField();
        txtFechaEntrega = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        pnlPendientes = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablePendientes = new javax.swing.JTable();
        pnlActualizar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtCodigoActualizar = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lbInfoTarea = new javax.swing.JLabel();
        chkResuelta = new javax.swing.JCheckBox();
        btnEliminar = new javax.swing.JButton();
        pnlFinalizados = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFinalizadas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        pnlMenu.setBackground(new java.awt.Color(33, 37, 41));
        pnlMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        pnlMenu.setPreferredSize(new java.awt.Dimension(160, 720));
        pnlMenu.setLayout(new java.awt.BorderLayout());

        pnlBotones.setBackground(new java.awt.Color(33, 37, 41));
        pnlBotones.setLayout(new java.awt.GridLayout(0, 1, 0, 15));

        btnMenuNuevaTarea.setBackground(new java.awt.Color(33, 37, 41));
        btnMenuNuevaTarea.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuNuevaTarea.setText("Nueva tarea");
        btnMenuNuevaTarea.setContentAreaFilled(false);
        btnMenuNuevaTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuNuevaTareaActionPerformed(evt);
            }
        });
        pnlBotones.add(btnMenuNuevaTarea);

        btnMenuPendientes.setBackground(new java.awt.Color(33, 37, 41));
        btnMenuPendientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuPendientes.setText("Pendientes");
        btnMenuPendientes.setContentAreaFilled(false);
        btnMenuPendientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuPendientesActionPerformed(evt);
            }
        });
        pnlBotones.add(btnMenuPendientes);

        btnMenuActualizar.setBackground(new java.awt.Color(33, 37, 41));
        btnMenuActualizar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuActualizar.setText("Actualizar");
        btnMenuActualizar.setContentAreaFilled(false);
        btnMenuActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActualizarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnMenuActualizar);

        btnMenuFinalizadas.setBackground(new java.awt.Color(33, 37, 41));
        btnMenuFinalizadas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnMenuFinalizadas.setText("Finalizadas");
        btnMenuFinalizadas.setContentAreaFilled(false);
        btnMenuFinalizadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuFinalizadasActionPerformed(evt);
            }
        });
        pnlBotones.add(btnMenuFinalizadas);

        pnlMenu.add(pnlBotones, java.awt.BorderLayout.CENTER);

        jLabel8.setForeground(new java.awt.Color(100, 100, 100));
        jLabel8.setText("[T] GestCourse v1.0 ");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 20, 0));
        pnlMenu.add(jLabel8, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlMenu, java.awt.BorderLayout.LINE_START);

        pnlContenedor.setBackground(new java.awt.Color(248, 249, 250));
        pnlContenedor.setLayout(new java.awt.CardLayout());

        pnlCrear.setBackground(new java.awt.Color(248, 249, 250));
        pnlCrear.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(33, 37, 41));
        jLabel2.setText("Panel de creación de tarea pendiente.");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 30, 0));

        jLabel1.setForeground(new java.awt.Color(33, 37, 41));
        jLabel1.setText("Título de la tarea:");

        jLabel3.setForeground(new java.awt.Color(33, 37, 41));
        jLabel3.setText("Módulo:");

        jLabel4.setForeground(new java.awt.Color(33, 37, 41));
        jLabel4.setText("Fecha de creación:");

        jLabel5.setForeground(new java.awt.Color(33, 37, 41));
        jLabel5.setText("Fecha de entrega:");

        jLabel6.setForeground(new java.awt.Color(33, 37, 41));
        jLabel6.setText("Prioridad:");

        txtTitulo.setBackground(new java.awt.Color(248, 249, 250));

        buttonGroup1.add(rbAlta);
        rbAlta.setForeground(new java.awt.Color(33, 37, 41));
        rbAlta.setText("Alta");

        buttonGroup1.add(rbMedia);
        rbMedia.setForeground(new java.awt.Color(33, 37, 41));
        rbMedia.setText("Media");
        rbMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMediaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbBaja);
        rbBaja.setForeground(new java.awt.Color(33, 37, 41));
        rbBaja.setText("Baja");

        cbModulo.setBackground(new java.awt.Color(248, 249, 250));
        cbModulo.setForeground(new java.awt.Color(33, 37, 41));
        cbModulo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Base de Datos", "Lenguajes de marcas (LMSGI)", "Digitalización (DASP)", "Entornos de Desarrollo", "Itinerari per a l'ocupabilitat /FOL", "Programación", "Sistemas informáticos" }));

        txtFechaCreacion.setEditable(false);
        txtFechaCreacion.setBackground(new java.awt.Color(248, 249, 250));

        txtFechaEntrega.setBackground(new java.awt.Color(248, 249, 250));

        btnGuardar.setBackground(new java.awt.Color(0, 102, 102));
        btnGuardar.setForeground(new java.awt.Color(248, 249, 250));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCrearLayout = new javax.swing.GroupLayout(pnlCrear);
        pnlCrear.setLayout(pnlCrearLayout);
        pnlCrearLayout.setHorizontalGroup(
            pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCrearLayout.createSequentialGroup()
                        .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlCrearLayout.createSequentialGroup()
                                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFechaEntrega)
                                    .addComponent(txtFechaCreacion)))
                            .addGroup(pnlCrearLayout.createSequentialGroup()
                                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(25, 25, 25)
                                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCrearLayout.createSequentialGroup()
                                        .addComponent(rbAlta)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbMedia)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbBaja)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cbModulo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 387, Short.MAX_VALUE)))
                            .addGroup(pnlCrearLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardar)))
                        .addGap(43, 43, 43))
                    .addGroup(pnlCrearLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlCrearLayout.setVerticalGroup(
            pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCrearLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbAlta)
                    .addComponent(rbMedia)
                    .addComponent(rbBaja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbModulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaCreacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtFechaEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGuardar)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        pnlContenedor.add(pnlCrear, "cardCrear");

        pnlPendientes.setBackground(new java.awt.Color(248, 249, 250));
        pnlPendientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 30, 30, 30));
        pnlPendientes.setMinimumSize(new java.awt.Dimension(0, 0));
        pnlPendientes.setPreferredSize(new java.awt.Dimension(612, 729));
        pnlPendientes.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(33, 37, 41));
        jLabel7.setText("Lista de Tareas Pendientes");
        jLabel7.setToolTipText("");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 30, 0));
        jLabel7.setPreferredSize(new java.awt.Dimension(323, 56));
        pnlPendientes.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setBackground(new java.awt.Color(33, 37, 41));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 1, 1, 1));

        tablePendientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tablePendientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablePendientes);

        pnlPendientes.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pnlContenedor.add(pnlPendientes, "cardPendientes");

        pnlActualizar.setBackground(new java.awt.Color(248, 249, 250));
        pnlActualizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 30, 30, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(33, 37, 41));
        jLabel9.setText("Actualización y Depuración de Tareas");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 30, 0));

        jLabel10.setBackground(new java.awt.Color(248, 249, 250));
        jLabel10.setForeground(new java.awt.Color(33, 37, 41));
        jLabel10.setText("Código numérico:");

        txtCodigoActualizar.setBackground(new java.awt.Color(248, 249, 250));

        btnActualizar.setBackground(new java.awt.Color(0, 102, 102));
        btnActualizar.setForeground(new java.awt.Color(248, 249, 250));
        btnActualizar.setText("Actualizar");
        btnActualizar.setEnabled(false);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(0, 102, 102));
        btnBuscar.setForeground(new java.awt.Color(248, 249, 250));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lbInfoTarea.setForeground(new java.awt.Color(33, 37, 41));
        lbInfoTarea.setText("Esperando búsqueda...");

        chkResuelta.setForeground(new java.awt.Color(33, 37, 41));
        chkResuelta.setText("Marcar como finalizada.");
        chkResuelta.setEnabled(false);

        btnEliminar.setBackground(new java.awt.Color(0, 102, 102));
        btnEliminar.setForeground(new java.awt.Color(248, 249, 250));
        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.setMaximumSize(new java.awt.Dimension(82, 23));
        btnEliminar.setMinimumSize(new java.awt.Dimension(82, 23));
        btnEliminar.setPreferredSize(new java.awt.Dimension(82, 23));
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlActualizarLayout = new javax.swing.GroupLayout(pnlActualizar);
        pnlActualizar.setLayout(pnlActualizarLayout);
        pnlActualizarLayout.setHorizontalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlActualizarLayout.createSequentialGroup()
                        .addComponent(chkResuelta)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlActualizarLayout.createSequentialGroup()
                        .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbInfoTarea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlActualizarLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodigoActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlActualizarLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnActualizar)))
                        .addGap(38, 38, 38))))
        );

        pnlActualizarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnActualizar, btnEliminar});

        pnlActualizarLayout.setVerticalGroup(
            pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlActualizarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtCodigoActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInfoTarea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chkResuelta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(478, Short.MAX_VALUE))
        );

        pnlActualizarLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnActualizar, btnEliminar});

        pnlContenedor.add(pnlActualizar, "cardActualizar");

        pnlFinalizados.setBackground(new java.awt.Color(248, 249, 250));
        pnlFinalizados.setBorder(javax.swing.BorderFactory.createEmptyBorder(60, 30, 30, 30));
        pnlFinalizados.setLayout(new java.awt.BorderLayout());

        jLabel11.setBackground(new java.awt.Color(248, 249, 250));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(33, 37, 41));
        jLabel11.setText("Tareas Finalizadas");
        jLabel11.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 30, 0));
        pnlFinalizados.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        jScrollPane2.setBackground(new java.awt.Color(33, 37, 41));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(30, 1, 1, 1));

        tableFinalizadas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tableFinalizadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableFinalizadas);

        pnlFinalizados.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        pnlContenedor.add(pnlFinalizados, "cardFinalizados");

        getContentPane().add(pnlContenedor, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMediaActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (txtTitulo.getText().trim().isEmpty() || txtFechaEntrega.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, rellena el título y la fecha de entrega.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        } else if (!rbAlta.isSelected() && !rbMedia.isSelected() && !rbBaja.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una prioridad.", "Error de validación", JOptionPane.ERROR_MESSAGE);
        } else {
            String titulo = txtTitulo.getText().trim();
            String modulo = cbModulo.getSelectedItem().toString();
            String fechaCre = txtFechaCreacion.getText();
            String fechaEnt = txtFechaEntrega.getText().trim();
            
            String prioridad = "";
            if (rbAlta.isSelected()) prioridad = "Alta";
            else if (rbMedia.isSelected()) prioridad = "Media";
            else if (rbBaja.isSelected()) prioridad = "Baja";

            int nuevoCodigo = 1;
            for (Tarea t : controlador.obtenerTodasLasTareas()) {
                if (t.getCodigo() >= nuevoCodigo) {
                    nuevoCodigo = t.getCodigo() + 1;
                }
            }

            Tarea nuevaTarea = new Tarea(nuevoCodigo, titulo, prioridad, modulo, fechaCre, fechaEnt);
            controlador.registrarTarea(nuevaTarea);

            JOptionPane.showMessageDialog(this, "Tarea guardada con éxito. Código asignado: " + nuevoCodigo, "Éxito", JOptionPane.INFORMATION_MESSAGE);

            txtTitulo.setText("");
            txtFechaEntrega.setText("");
            buttonGroup1.clearSelection();
            cbModulo.setSelectedIndex(0);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnMenuPendientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuPendientesActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(pnlContenedor.getLayout());
        cl.show(pnlContenedor, "cardPendientes");
        
        actualizarTabla(tablePendientes, "Pendiente");
    }//GEN-LAST:event_btnMenuPendientesActionPerformed

    private void btnMenuNuevaTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuNuevaTareaActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(pnlContenedor.getLayout());
        cl.show(pnlContenedor, "cardCrear");
    }//GEN-LAST:event_btnMenuNuevaTareaActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
     if (!chkResuelta.isSelected()) {
            JOptionPane.showMessageDialog(this, "Debes marcar el checkbox para confirmar que la tarea está resuelta.", "Falta confirmación", JOptionPane.WARNING_MESSAGE);
        } else {
            int codigoBuscado = Integer.parseInt(txtCodigoActualizar.getText().trim());
            boolean actualizada = false;
            int i = 0;
            java.util.ArrayList<Tarea> tareas = controlador.obtenerTodasLasTareas();

            while (i < tareas.size() && !actualizada) {
                Tarea t = tareas.get(i);
                if (t.getCodigo() == codigoBuscado) {
                    t.setEstado("Finalizada");
                    controlador.actualizarMemoria();
                    actualizada = true;
                    
                    JOptionPane.showMessageDialog(this, "Tarea [" + codigoBuscado + "] actualizada a Finalizada correctamente.", "Actualización Exitosa", JOptionPane.INFORMATION_MESSAGE);
                    
                    txtCodigoActualizar.setText("");
                    lbInfoTarea.setText("Esperando búsqueda...");
                    chkResuelta.setSelected(false);
                    chkResuelta.setEnabled(false);
                    btnActualizar.setEnabled(false);
                    btnEliminar.setEnabled(false);
                    
                    actualizarTabla(tablePendientes, "Pendiente");
                }
                i++;
            }
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnMenuActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActualizarActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(pnlContenedor.getLayout());
        cl.show(pnlContenedor, "cardActualizar");
    }//GEN-LAST:event_btnMenuActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String codigoStr = txtCodigoActualizar.getText().trim();
    
        if (codigoStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, introduce un código para buscar.", "Campo vacío", JOptionPane.WARNING_MESSAGE);
        } else {
            try {
                int codigoBuscado = Integer.parseInt(codigoStr);
                boolean encontrada = false;
                int i = 0;
                java.util.ArrayList<Tarea> tareas = controlador.obtenerTodasLasTareas();

                while (i < tareas.size() && !encontrada) {
                    Tarea t = tareas.get(i);
                    if (t.getCodigo() == codigoBuscado) {
                        encontrada = true;
                        lbInfoTarea.setText("<html><b>Título:</b> " + t.getTitulo() + "<br><b>Módulo:</b> " + t.getModulo() + "<br><b>Estado actual:</b> " + t.getEstado() + "</html>");
                        
                        if (t.getEstado().equals("Finalizada")) {
                            chkResuelta.setSelected(true);
                            chkResuelta.setEnabled(false);
                            btnActualizar.setEnabled(false);
                            btnEliminar.setEnabled(true);
                            JOptionPane.showMessageDialog(this, "Esta tarea ya consta como resuelta en los registros.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                        } else {
                            chkResuelta.setSelected(false);
                            chkResuelta.setEnabled(true);
                            btnActualizar.setEnabled(true);
                            btnEliminar.setEnabled(true);
                        }
                    }
                    i++;
                }

                if (!encontrada) {
                    JOptionPane.showMessageDialog(this, "No se ha encontrado ninguna tarea con el código [" + codigoBuscado + "].", "Búsqueda fallida", JOptionPane.ERROR_MESSAGE);
                    lbInfoTarea.setText("Esperando búsqueda...");
                    chkResuelta.setEnabled(false);
                    btnActualizar.setEnabled(false);
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "El código debe ser un valor numérico.", "Error de formato", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnMenuFinalizadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuFinalizadasActionPerformed
        java.awt.CardLayout cl = (java.awt.CardLayout)(pnlContenedor.getLayout());
        cl.show(pnlContenedor, "cardFinalizados");
        
        actualizarTabla(tableFinalizadas, "Finalizada");
    }//GEN-LAST:event_btnMenuFinalizadasActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int codigoBuscado = Integer.parseInt(txtCodigoActualizar.getText().trim());

    int confirmacion = JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de que deseas eliminar permanentemente la tarea [" + codigoBuscado + "]?", 
        "Confirmar Eliminación", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.WARNING_MESSAGE);

    if (confirmacion == JOptionPane.YES_OPTION) {
        boolean exito = controlador.eliminarTarea(codigoBuscado);
        
        if (exito) {
            JOptionPane.showMessageDialog(this, "Tarea eliminada de los registros.", "Purga completada", JOptionPane.INFORMATION_MESSAGE);

            txtCodigoActualizar.setText("");
            lbInfoTarea.setText("Esperando búsqueda...");
            chkResuelta.setSelected(false);
            chkResuelta.setEnabled(false);
            btnActualizar.setEnabled(false);
            btnEliminar.setEnabled(false);

            actualizarTabla(tablePendientes, "Pendiente");
            actualizarTabla(tableFinalizadas, "Finalizada");
        } else {
            JOptionPane.showMessageDialog(this, "Error: No se pudo localizar la tarea para su eliminación.", "Fallo del sistema", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            System.err.println("Error al cargar la interfaz visual: " + ex.getMessage());
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ventana_principal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenuActualizar;
    private javax.swing.JButton btnMenuFinalizadas;
    private javax.swing.JButton btnMenuNuevaTarea;
    private javax.swing.JButton btnMenuPendientes;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbModulo;
    private javax.swing.JCheckBox chkResuelta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbInfoTarea;
    private javax.swing.JPanel pnlActualizar;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlCrear;
    private javax.swing.JPanel pnlFinalizados;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlPendientes;
    private javax.swing.JRadioButton rbAlta;
    private javax.swing.JRadioButton rbBaja;
    private javax.swing.JRadioButton rbMedia;
    private javax.swing.JTable tableFinalizadas;
    private javax.swing.JTable tablePendientes;
    private javax.swing.JTextField txtCodigoActualizar;
    private javax.swing.JTextField txtFechaCreacion;
    private javax.swing.JTextField txtFechaEntrega;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
